const fs = require('fs');
const path = require('path');
const { Document, Packer, Paragraph, PageBreak, TextRun } = require('docx');
const { executeGeminiCode } = require('./src/renderer_v2');
const crypto = require('crypto');

// Helper to get cache path (copied from index_v2)
function getCachePath(imagePath) {
    const hash = crypto.createHash('md5').update(imagePath).digest('hex');
    return path.join(__dirname, 'temp_code', `${hash}.js`);
}

async function debugCorruptDocx(documentPrefix) {
    const framesDir = path.join(__dirname, 'uploads/temp_frames');
    const cacheDir = path.join(__dirname, 'temp_code');

    if (!fs.existsSync(framesDir) || !fs.existsSync(cacheDir)) {
        console.error("Error: 'uploads/temp_frames' or 'temp_code' directory not found.");
        return;
    }

    console.log(`
==============================================
DEBUGGING CORRUPT DOCX: ${documentPrefix}
==============================================`);

    const imagesForDoc = fs.readdirSync(framesDir)
        .filter(f => f.startsWith(documentPrefix) && f.endsWith('.png'))
        .map(f => ({
            name: f, 
            path: path.join(framesDir, f),
            pageNum: parseInt(f.match(/-(\d+)\.png$/)[1]) // Extract page number
        }))
        .sort((a, b) => a.pageNum - b.pageNum);

    if (imagesForDoc.length === 0) {
        console.error("No image frames found for the specified document prefix.");
        return;
    }

    console.log(`Found ${imagesForDoc.length} pages/frames.`);

    let finalChildren = [];

    for (const imgInfo of imagesForDoc) {
        const pageNum = imgInfo.pageNum;
        const imagePath = imgInfo.path;
        const cacheFilePath = getCachePath(imagePath);

        console.log(`
--- Processing Page ${pageNum} (${imgInfo.name}) ---
`);

        if (!fs.existsSync(cacheFilePath)) {
            console.warn(`⚠️ Cache file missing for Page ${pageNum}. Skipping.`);
            continue;
        }

        try {
            const codeString = fs.readFileSync(cacheFilePath, 'utf-8');
            console.log(`Loading cached code for Page ${pageNum}.`);
            
            let pageChildren = [];
            try {
                pageChildren = executeGeminiCode(codeString);
                console.log(`✅ Code executed successfully for Page ${pageNum}. Found ${pageChildren.length} children.`);
            } catch (execErr) {
                console.error(`❌ Code execution failed for Page ${pageNum}: ${execErr.message}`);
                console.error(`Offending Code Sample (Page ${pageNum}):\n${codeString.substring(0, 500)}...`);
                // Optionally, save bad code to a debug file
                fs.writeFileSync(path.join(__dirname, `debug_bad_code_page_${pageNum}.js`), codeString);
                continue; // Skip this page
            }
            
            if (pageChildren.length === 0) {
                console.warn(`⚠️ Page ${pageNum} generated no children. Skipping.`);
                continue;
            }

            finalChildren = finalChildren.concat(pageChildren);
            // Add a page break between pages for better debug visibility
            finalChildren.push(new Paragraph({ children: [new PageBreak()] }));

        } catch (fileReadErr) {
            console.error(`❌ Error reading cache for Page ${pageNum}: ${fileReadErr.message}. Skipping.`);
            continue;
        }
    }

    if (finalChildren.length === 0) {
        console.error(`
💀 No valid children collected. Cannot generate DOCX.`);
        return;
    }

    console.log(`
✅ All valid pages processed. Total children: ${finalChildren.length}. Attempting final DOCX packing...
`);

    try {
        const doc = new Document({
            sections: [{ children: finalChildren }]
        });
        const buffer = await Packer.toBuffer(doc);
        const outputPath = `Debug_${documentPrefix}_Salvaged_${Date.now()}.docx`;
        fs.writeFileSync(outputPath, buffer);
        console.log(`
🎉 Successfully generated debug DOCX: ${outputPath}`);
    } catch (packErr) {
        console.error(`
❌ DOCX Packer failed: ${packErr.message}`);
        console.error(`This indicates an invalid document structure generated by Gemini.`);
        console.error(`Try inspecting the 'debug_bad_code_page_X.js' files for clues.`);
    }
}

// To run: node debug_corrupt_docx.js <document_filename_prefix_from_uploads>
// Example: node debug_corrupt_docx.js 1765033604237-L39_STOLLE_25-149_final signed both_flat_gs
const docPrefix = process.argv[2];
if (!docPrefix) {
    console.error("Usage: node debug_corrupt_docx.js <document_filename_prefix_from_uploads>");
    console.error("Example: node debug_corrupt_docx.js 1765033604237-L39_STOLLE_25-149_final signed both_flat_gs");
} else {
    debugCorruptDocx(docPrefix);
}
